### ISSUE TITLE
Rename uport-core-js to uport-transports

### ISSUE THREAD

**Issue by pelle** [uport-project/uport-transports#4]
We already have uport-js and uport-core-js is just too confusing.

Before we release major versions we need to rename this. I suggest uport-transports, but open to suggestions.

**Comment by zachferland** [comment]
completely agree! the original plan was to also pull credentials as a module into uport-core, so we wouldn't have those two names. I wouldn't call the whole thing transports, the intention was for transports to only be one module in there. We could pull transports out as a separate module and call it uport-transports. But on the other hand I think a makes a lot sense to still have a place for all modules and/or a mix of smaller ones (or until they get bigger). I also wanted a more general spot to place smaller pieces of useful code/utils/etc

also just noticed uport-js changing to uport-credentials? makes sense to me, do want to keep this as uport-core then, or consider changing still?

**Comment by pelle** [comment]
@zachferland we should go ahead with this change asap. We don't want it to become a legacy support issue

**Comment by localredhead** [comment]
https://github.com/uport-project/uport-core-js/pull/7

**Comment by pelle** [comment]
We should also update uport-connect with this

**Comment by localredhead** [comment]
https://github.com/uport-project/uport-connect/pull/162/commits/bc9d278f6f538926bf26a013a6791048de4bdb5f

**Comment by Eseoghene** [comment]
1
